#!/bin/bash
# Launcher for Primer Designer
# Auto-generated by install.py

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON_PATH="$SCRIPT_DIR/venv/bin/python"

if [ ! -f "$PYTHON_PATH" ]; then
    echo "Error: Virtual environment not found at $SCRIPT_DIR/venv"
    echo "Please run: python install.py"
    exit 1
fi

echo "Starting Primer Designer..."
"$PYTHON_PATH" "$SCRIPT_DIR/main.py"
